version: "3.8"

services:
  api:
    build: ./app
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://db/myTestDB
    volumes:
      - ./app:/app
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - recordsDB:/data/db
volumes:
  recordsDB:
